### ISSUE TITLE
Thesis pseudo-code problem

### ISSUE THREAD

**Issue by love381** [feferna/DNNDeepeningPruning#1]
Read the paper corresponding to the code and found that there is a problem in Algorithm 4.

18 for i = 1 t o l e n (P) do
19 if Pi.isDominated = True then
20 F ← F ∪ Pi;
21 end
22 end
Pi.isDominated = True   I think it should be changed to  Pi.isDominated = False 
Because the solution that is not dominated is thePareto front set, called F。

**Comment by feferna** [comment]
Dear love381,

Yes, you are right. It should be Pi.isDominated = False in the paper.

However, this problem is corrected in the code in this repository. See line 66 of the file DeepPruningESWIN.py.

Best,
Francisco Fernandes

**Comment by love381** [comment]
Dear Fernandes，
I will take a good look at the source code, thank you for your affirmation.
Best,
yameng zhu
